---
collections: 
  - name: awx.awx
  - name: infra.controller_configuration
  - name: cisco.ios
  - name: cisco.aci
  - name: cisco.nxos
  - name: f5networks.f5_modules
  - name: paloaltonetworks.panos