---

- name: Listen for alerts using alert manager
  hosts: all

  sources:
    #- ansible.eda.alertmanager:
    #    host: 0.0.0.0
    #    port: 5000
    - ansible.eda.file:
      files:
        - /var/log/nic.yml
  rules:
    - name: Run playbook to start NIC
      condition:
        all: 
          - facts.ansible_net_interfaces.[0].state == "down" 
          - facts.gathered.enabled == "false"

      action:
        debug:
        
        #run_job_template:
        #  name: "nxos_nic_up"
        #  organization: Default
        #  job_args:
        #    extra_vars:
                
