---

- name: Listen for alerts using alert manager
  hosts: all

  sources:
    - ansible.eda.range:
        limit: 5  
    #- ansible.eda.alertmanager:
    #    host: localhost
    #    port: 5001
    #- ansible.eda.file:
    #  files:
    #    - /var/log/nic.yml
  rules:
    - name: Run playbook to start NIC
      condition: event.i == 1

        #all:

          #- facts.ansible_net_interfaces.[0].state == "down" 
          #- facts.gathered.enabled == "false"
      action:
        #run_playbook:
        #  name: ansible.eda.nxos_nic_up
          
          #"playbooks/nxos_nic_up.yml"

        run_job_template:
          name: "nxos_nic_up"
          organization: Default
        #  job_args:
        #    extra_vars:
                
