---
- name: Set Up Kafka and ZooKeeper with Podman
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure "messaging" network exists
      containers.podman.podman_network:
        name: messaging
        state: present


    - name: Start the ZooKeeper container
      containers.podman.podman_container:
        name: zookeeper
        image: bitnami/zookeeper
        state: started
        env:
          ALLOW_ANONYMOUS_LOGIN: 'yes'
        ports:
          - "2181:2181"
        network: messaging


    - name: Start the Kafka container
      containers.podman.podman_container:
        name: kafka
        image: bitnami/kafka
        state: started
        env:
          ALLOW_PLAINTEXT_LISTENER: 'yes'
          KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
          KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
        ports:
          - "9092:9092"
        network: messaging