---


  - hosts: all
    tasks:
      - name: "restart nic"
        cisco.nxos.nxos_command:
          commands:
            #- "show version"
            #- "show int"
            - command: "config t"
            - command: "int Ethernet1/2"
            - command: "no shut"


