---


  - hosts: all
    tasks:
      - name: "restart nic"
        cisco.nxos.nxos_command:
          commands:
            #- "show version"
            - "show interfaces"
            #- "configure terminal"
            #- "int Ethernet1/2"
            #- "no shut"


